version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "-uuser", "-ppass", "ping", "-h", "db"]
      interval: 10s
      retries: 10
      timeout: 30s

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'iotdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uuser", "-ppass", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10
      timeout: 30s
